local dir = "ui"
require (dir .. '.filetype')
require (dir .. '.notify')
require (dir .. '.nvim-tree')
require (dir .. '.nvim-treesitter')
require (dir .. '.orgmode')
require (dir .. '.nvim-telescope')
require (dir .. '.colorizer')
require (dir .. '.lualine')
