#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    layout                       bsp


# mouse
yabai -m config    mouse_follows_focus          on
yabai -m config    focus_follows_mouse          off
yabai -m config    mouse_modifier               fn
yabai -m config    mouse_action1                move
yabai -m config    mouse_action2                resize
yabai -m config    mouse_drop_action            swap


# window behavior
yabai -m config  window_origin_display        default
yabai -m config  window_placement             second_child
yabai -m config  window_topmost               off
yabai -m config  window_shadow                off
yabai -m config  window_opacity               off
yabai -m config  window_animation_duration    0.0
yabai -m config  window_opacity_duration      0.0
yabai -m config  active_window_opacity        0.95
yabai -m config  normal_window_opacity        0.95


# window border
yabai -m config  window_gap                  03
yabai -m config  window_border_width         1
yabai -m config  window_border_radius        12
yabai -m config  window_border_blur          off
yabai -m config  window_border_hidpi         on
yabai -m config  window_border               off
# yabai -m config  active_window_border_color  0xff775759
yabai -m config  active_window_border_color  0xff3e5ea3
# yabai -m config  normal_window_border_color  0xff555555
yabai -m config  normal_window_border_color  0xfff9cdd4


# padding
yabai -m config  top_padding                   6
yabai -m config  bottom_padding                8
yabai -m config  left_padding                 10
yabai -m config  right_padding                10
yabai -m config  external_bar all:24:0


# app specific setting.
# try to use yabai -m query --windows for window reference
# apps that shall be float
yabai -m rule --add app="^(MacForge|App Store|Xnip|Macs Fan Control|Fig)$" manage=off
yabai -m rule --add app="^(Calculator|计算器|安装器|Activity Monitor|活动监视器)$" manage=off
yabai -m rule --add app="^(Calendar|日历)$" manage=off
yabai -m rule --add app="^(Docker Desktop)$" manage=off
yabai -m rule --add app="^(问题报告程序)$" manage=off
yabai -m rule --add app="^(System Settings|系统设置|系统信息)$" manage=off
yabai -m rule --add app="^(Alfred Preferences|Codye|Keka|Nutstore|坚果云|Dropbox|Typora|CotEditor)$" manage=off
yabai -m rule --add app="^(TencentMeeting|腾讯会议|TeamViewer|TeamViewer QuickSupport)$" manage=off
# yabai -m rule --add label="float-wechat-nonchat" app="^微信$" title!="^微信 \(聊天\)$" manage=off
yabai -m rule --add app="^微信$" manage=off
yabai -m rule --add app="^(Day One)$" title="^(通用|安全|同步|日记本|显示|提醒|支持)$" manage=off
# do not track Inkscape windows other than the main workspace
yabai -m rule --add app="^(Inkscape)$" title!="^(.* - Inkscape)$" manage=off
# float all preferences
yabai -m rule --add title="(Preferences|设置)$" manage=off
# float all Finder Info window
yabai -m rule --add app="^(Finder|访达)$" title="简介$" manage=off
# float the mini music player and other small tools
yabai -m rule --add title="^(迷你播放程序)$" manage=off
yabai -m rule --add app="^(Reminders|提醒事项|Dictionary|词典|数码测色计|G2FA|ChatGPT|天气|Weather|qtgrace)$" manage=off

# temporary rule to float and topmost flypy keyboard
yabai -m rule --add title="^hejp_flypy.png$" manage=off sticky=on layer=above

# Fix App to space (desktop)
yabai -m rule --add app="^(Safari|Firefox|Google Chrome)$" space=1
# yabai -m rule --add title="^(.*DeepL Translate.*)$" manage=off
yabai -m rule --add app="^(Code|Xcode|VSCodium)$" space=2
yabai -m rule --add app="^(iTerm2|kitty|Alacritty)$" space=^3
yabai -m rule --add app="^(PDF Viewer)$" space=4
yabai -m rule --add app="^(备忘录|Notes|Day One)$" space=5
yabai -m rule --add app="^(IINA|OBS Studio|QuickTime Player)$" manage=off
yabai -m rule --add app="^(DaVinci Resolve)$" space=6
yabai -m rule --add app="^(Mail)$" space=8
yabai -m rule --add app="^(音乐|Music|Spotify)$" space=9
yabai -m rule --add app="^(微信|WeChat|Slack|WhatsApp|Discord)$" space=10
# Disable mouse follow for Clocker tray menu
yabai -m rule --add app="^(Clocker)$" mouse_follows_focus=off
yabai -m rule --add app="^(Steam)$" space=6 mouse_follows_focus=off


# space naming
yabai -m space 1 --label www
yabai -m space 2 --label code
yabai -m space 3 --label term
yabai -m space 4 --label read
yabai -m space 5 --label note
yabai -m space 6 --label media
yabai -m space 7 --label design
yabai -m space 8 --label 信
yabai -m space 9 --label 音
yabai -m space 10 --label 訊

# refresh my Übersicht bar when the space changes
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"polybar-left-bar-coffee\"'"

echo "yabai configuration loaded.."

