# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Fig pre block. Keep at the top of this file.
# # If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export DYLD_LIBRARY_PATH
export OMP_NUM_THREADS=1

# MPICH always uses GCC, not Apple Clang
export MPICH_FC=gfortran-13
export MPICH_CC=gcc-13
export MPICH_CXX=g++-13

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Ignore files with particular suffixes for vi/vim/nvim
zstyle ':completion:*:*:(vi|vim|nvim|git):*' file-patterns \
	'^*.(x|aux|nav|snm|pdf|dvi|bbl|mod|pyc|o|exe|fdb_latexmk|synctex.gz|blg|toc|fls|bcf|gif|png|jpg|jpeg|eps|dSYM):source-files' \
	'*:all-files'
# Ignore files with particular suffixes for open
zstyle ':completion:*:*:(open|xdg-open):*' file-patterns \
	'^*.(x|aux|nav|snm|dvi|bbl|mod|pyc|o|exe|fdb_latexmk|synctex.gz|blg|toc|fls|bcf|eps|dSYM):source-files' \
	'*:all-files'

# zplug to handle plugins
export ZPLUG_HOME=/opt/homebrew/opt/zplug
if [[ -d "$ZPLUG_HOME" ]]; then
  source $ZPLUG_HOME/init.zsh

  # plugins provided by oh-my-zsh
  zplug "plugins/git", from:oh-my-zsh
  zplug "plugins/ripgrep", from:oh-my-zsh
  zplug "plugins/autojump", from:oh-my-zsh
  zplug "plugins/changelog", from:oh-my-zsh

  # external plugins
  # zplug "marlonrichert/zsh-autocomplete", defer:0
  zplug "zsh-users/zsh-completions"
  zplug "zsh-users/zsh-autosuggestions"
  zplug "zsh-users/zsh-history-substring-search"
  # password generation https://ss64.com/pass
  zplug "salsifis/ss64-password-generators", use:"zsh/*.zsh"
  zplug "hlissner/zsh-autopair", defer:2
  zplug romkatv/powerlevel10k, as:theme, depth:1

  # Install plugins if there are plugins that have not been installed
  if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
      echo; zplug install
    fi
  fi
  # Then, source plugins and add commands to $PATH
  # zplug load --verbose
  zplug load
else
  brew install zplug
fi

[[ -d "$ZSH" ]] && source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# direnv completion
if command -v direnv 1>/dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

export PATH="$HOME/scripts:$PATH"
export PYTHONPATH="$HOME/scripts:$PYTHONPATH"

source $HOMEBREW_PREFIX/opt/modules/init/zsh
# [[ ! -f "$MYRM/scripts/check_inbox" ]] || "$MYRM/scripts/check_inbox"
# [[ ! -f "$MYRM/scripts/check_leftwork" ]] || "$MYRM/scripts/check_leftwork"
# module load ssh
module load mushroom

[[ ! -f "$HOME/.alias" ]] || source "$HOME/.alias"

source /opt/homebrew/opt/asdf/libexec/asdf.sh

# module load intel/2023.1.0
# gcc/latest  mpich/4.1.1-intel-2023.1.0  scalapack/2.2.0-intel-2023.1.0-mpich-4.1.1

# Fig post block. Keep at the bottom of this file.
# # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
